source: build

collections:
  products:
    title: Products
    output: true
    permalink: /:collection/:name/
  categories:
    title: Categories
    output: true
    permalink: /:collection/:name/
  news:
    title: News
    output: true
    permalink: /:collection/:name/
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: product
- scope:
    path: ''
    type: categories
  values:
    layout: category
- scope:
    path: ''
    type: news
  values:
    layout: news
